class Solution {
        public int countRangeSum(int[] nums, int lower, int upper) {
                int n=nums.length;
                        long [] sum=new long[n+1];
                                for(int i=0;i<n;i++){
                                            sum[i+1]=sum[i]+nums[i];
                                                    }return mergeSort(sum,0,n,lower,upper);
                                                        }
                                                            private int mergeSort(long[] sum, int low, int high, int lower, int upper){
                                                                    if (low>= high){
                                                                                return 0;
                                                                                        }int mid=(high+1-low)/2+low;
                                                                                                int count=mergeSort(sum,low,mid-1,lower,upper)+ mergeSort(sum,mid,high,lower,upper);
                                                                                                        int start_index=mid;
                                                                                                                int end_index=mid;
                                                                                                                        for(int i=low;i<mid;i++){
                                                                                                                                    while(start_index<=high && sum[start_index]-sum[i]<lower){
                                                                                                                                                    start_index++;
                                                                                                                                                                }while(end_index<=high && sum[end_index]-sum[i]<=upper){
                                                                                                                                                                                end_index++;
                                                                                                                                                                                            }count+= end_index-start_index;
                                                                                                                                                                                                    }merge(sum,low,mid-1,mid,high);
                                                                                                                                                                                                            return count;
                                                                                                                                                                                                                }
                                                                                                                                                                                                                    private void merge(long[] sum, int low1, int high1, int low2, int high2){
                                                                                                                                                                                                                            long[] helper= new long[high2-low1+1];
                                                                                                                                                                                                                                    int index=0;
                                                                                                                                                                                                                                            int index1=low1; int index2= low2;
                                                                                                                                                                                                                                                    while(index1<=high1 && index2<=high2){
                                                                                                                                                                                                                                                                if(sum[index1]<=sum[index2]){
                                                                                                                                                                                                                                                                                helper[index++]=sum[index1++];
                                                                                                                                                                                                                                                                                            }else{
                                                                                                                                                                                                                                                                                                            helper[index++]=sum[index2++];
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                }while(index1<=high1){
                                                                                                                                                                                                                                                                                                                                            helper[index++]=sum[index1++];
                                                                                                                                                                                                                                                                                                                                                    }while(index2<=high2){
                                                                                                                                                                                                                                                                                                                                                                helper[index++]=sum[index2++];
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                System.arraycopy(helper,0,sum,low1,high2-low1+1);
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    
}