class Solution {
        public int countBeautifulPairs(int[] nums) {
                int n = nums.length;
                        int count=0;
                                for(int i=0;i<n;i++)
                                            {
                                                            int x = nums[i];
                                                                            int num1=0;
                                                                                            while(x>0)
                                                                                                            {
                                                                                                                                num1 = x%10;
                                                                                                                                                    x=x/10;
                                                                                                                                                                    }
                                                                                                                                                                                    for(int j=i+1;j<n;j++)
                                                                                                                                                                                                        {
                                                                                                                                                                                                                                int num2 = nums[j]%10;
                                                                                                                                                                                                                                                        int m = Math.min(num1,num2);
                                                                                                                                                                                                                                                                                boolean flag = true;
                                                                                                                                                                                                                                                                                                        for(int k=2;k<=m;k++)
                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                    if(num1%k==0 && num2%k==0)
                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                        flag = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(flag)count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return count;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
